spring:
  datasource:
    password: password
    username: user
    url: jdbc:postgresql://localhost:5432/elfes
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  image:
    storage:
      directory: images
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
